// <auto-generated />
using System;
using KinoEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KinoEF.Migrations
{
    [DbContext(typeof(KinoContext))]
    [Migration("20200405185011_Sala")]
    partial class Sala
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KinoEF.Models.Kino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaKina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kino");
                });

            modelBuilder.Entity("KinoEF.Models.Sala", b =>
                {
                    b.Property<int>("IdSali")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KinoId")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<string>("NazwaSali")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSali");

                    b.HasIndex("KinoId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("KinoEF.Models.Sala", b =>
                {
                    b.HasOne("KinoEF.Models.Kino", "Kino")
                        .WithMany("Sale")
                        .HasForeignKey("KinoId");
                });
#pragma warning restore 612, 618
        }
    }
}
